spring:
  mail:
    host: smtp.163.com
    username: qbs784784@163.com
    password: LF4JVi2qe99HVtNv
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: quboshi
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: "20021201"
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    verify:
      mail-limit: 60
  minio:
    endpoint: "http://localhost:9000"
    username: "minio"
    password: "password"